name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }}
    strategy:
      matrix:
        node:
          - 18
          - 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build and Lint
        run: yarn run-s build lint
        env:
          EFF_NO_LINK_RULES: true
          PARSER_NO_WATCH: true

      - name: Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
